### ISSUE TITLE
'charmap' codec can't encode character... error when using .write_report() 

### ISSUE THREAD

**Issue by jcdyer3** [credo-ai/credoai_lens#133]
## Expected Behavior
Assessment report is written to html file using utf-8 encoding for export into Credo AI Governance Tool. 

## Actual Behavior
When I initially ran my report, after the report was shown in the jupyter notebook, I gott a 'charmap' codec can't encode character '\ue6c6' in position 237531: character maps to <undefined> error (image attached). 

From my research and spot checking of the code I found that while Python 3.7+ default encoding is 'utf-8' most legacy windows systems default encoding is  cp1252 and this is inherited by python as the default encoding and used when the open function is run (https://stackoverflow.com/questions/42070668/python-3-default-encoding-cp1252) in the report.py file. 

I was able to fix this by changing my default encoder but in the interest of making the code environment agnostic, another option is to pass encoding = 'utf-8' when the open function is run similar to this:- open(<file_loc>,'w',encoding = 'utf8') 

## Steps to Reproduce the Problem

  1. Run through the quickstart assessment in 

-   local Jupyter notebook 
- using Python 3.7.13 
- on a windows machine.

  2. Observe output 

## Specifications

  - Version: 0.1.2
  - Platform: Local Jupyter Notebook, Windows Machine, Python 3.7.13

**Comment by jcdyer3** [comment]
Update: when my notebook reloads it requires that I run: 
```
import _locale
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])``
```
which could be prohibitive in a deployment environment

**Comment by IanAtCredo** [comment]
@jcdyer3 , reporting functionality is being significantly changed in the next upload which will make this issue irrelevant. Stay tuned
