### ISSUE TITLE
Fresh environment install with environment.yml leads to import errors in quickstart.ipynb

### ISSUE THREAD

**Issue by esherman-credo** [credo-ai/credoai_lens#192]
## Expected Behavior
quickstart.ipynb should run after creating a conda environment with `conda create env --file environment.yml`

## Actual Behavior

![image](https://user-images.githubusercontent.com/114082449/193961050-eac91ae7-fc6c-46b9-9781-d244fa017281.png)

Import error.

## Steps to Reproduce the Problem
`conda create env --file environment.yml`
Then run quickstart.ipynb first two cells

## Specifications

  - Version: Pandas = 1.5.0

 **I suspect we need to enforce Pandas == 1.4.4 in pip/environment.yml**

**Comment by IanAtCredo** [comment]
We have deprioritized environment.yml, but this shouldn't be happening. Is this still an issue @esherman-credo ?

**Comment by esherman-credo** [comment]
It seems to work. I did a fresh install using conda and the yml file and got through running quickstart.ipynb without running into the above issue.

I AM getting a different error now with `process_metrics()` (indirectly, when calling `Lens.add()`. It's an issue with self not being an argument in `process_metrics()`.

I think we fixed this in develop and it hasn't been pushed to main yet?

Develop: https://github.com/credo-ai/credoai_lens/blob/develop/credoai/evaluators/performance.py#L225 and https://github.com/credo-ai/credoai_lens/blob/develop/credoai/evaluators/performance.py#L184
Main: https://github.com/credo-ai/credoai_lens/blob/main/credoai/evaluators/performance.py#L226 and https://github.com/credo-ai/credoai_lens/blob/main/credoai/evaluators/performance.py#L185
