### ISSUE TITLE
Logger lines in performance.py throw an error

### ISSUE THREAD

**Issue by esherman-credo** [credo-ai/credoai_lens#203]
https://github.com/credo-ai/credoai_lens/blob/f73d4bf75a4a2aac8944031cc071459e7f5d3f1f/credoai/evaluators/performance.py#L226 and https://github.com/credo-ai/credoai_lens/blob/f73d4bf75a4a2aac8944031cc071459e7f5d3f1f/credoai/evaluators/performance.py#L239 both use `self` which is not passed to this static method. Throws a `self not Defined` error.

Likely introduced during recent changes to process_metrics handling?

More details:
On a fresh conda environment for gini feature development with fresh install of lens. Running quickstart.ipynb

This cell:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/114082449/196287263-169a2676-a2bc-4e97-a924-0453692149ce.png">

(Part of) Traceback:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/114082449/196287345-a977ac68-9ef7-41d2-b8fd-582c58846df2.png">

**Comment by fabrizio-credo** [comment]
@IanAtCredo I will fix this, it is only triggered by `equal_opportunity` in the example above, which is a **FAIRNESS** type metric. I will update tests to include this type of metric as well.

@esherman-credo good find 🙌

**Comment by esherman-credo** [comment]
@fabrizio-credo Ian suggested I just take care of it with the gini pr. See https://github.com/credo-ai/credoai_lens/pull/205
