### ISSUE TITLE
Sensitive features tied to assessment data

### ISSUE THREAD

**Issue by IanAtCredo** [credo-ai/credoai_lens#213]
## Expected Behavior

When training/assessment dataset are passed, Lens creates versions of the evaluator for each dataset with the appropriate sensitive feature. It seems this functionality should exist in `_cycle_add_through_ds_feat`

## Actual Behavior

Sensitive features are specified in [relationship to the assessment dataset](https://github.com/credo-ai/credoai_lens/blob/develop/credoai/lens/lens.py#L62). This breaks down when only training is specified OR when assessment and training have different sensitive features.

**Comment by fabrizio-credo** [comment]
@IanAtCredo is there a ticket for this? 

- What is the rational for using different sensitive features in training vs assessment? 
- What would be the expected behavior? -> Cycle separately for each of the dataset?
