### ISSUE TITLE
Error loading library due to updates in most recent fairlearn's version

### ISSUE THREAD

**Issue by angeliney** [credo-ai/credoai_lens#336]
## Expected Behavior
loading library works successfully

## Actual Behavior
Error due to fairlearn updating their API in v0.9.0
```
[/usr/local/lib/python3.10/dist-packages/credoai/modules/constants_metrics.py](https://localhost:8080/#) in <module>
     58     "gini_coefficient": gini_coefficient_discriminatory,
     59     "matthews_correlation_coefficient": sk_metrics.matthews_corrcoef,
---> 60     "overprediction": fl_metrics._mean_overprediction,
     61     "precision_score": sk_metrics.precision_score,
     62     "roc_auc_score": sk_metrics.roc_auc_score,

AttributeError: module 'fairlearn.metrics' has no attribute '_mean_overprediction'
```

## Steps to Reproduce the Problem

  1. `pip install credoai-lens[full]`
  2. `from credoai.evaluators import ModelFairness, Performance`
 

## Specifications
  - Version: 1.1.8
  - Platform: Google Colab, python 3.10

## Workaround
Downgrade fairlearn version back to before the changes occur:
`pip install fairlearn==0.8.0`

**Comment by fabrizio-credo** [comment]
@angeliney, thanks for your interest in Lens. Unfortunately, this package is no longer maintained.
I will therefore close this issue.
